name: play2travel
description: "Uma nova app de turismo interativo (PAP)."
publish_to: 'none' # Impede a publicação acidental no pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Os pacotes que estamos a usar para o Mapa
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  firebase_core: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # O pacote mágico para mudar o ícone da app
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Aqui dizemos ao Flutter para ler a pasta onde tens a tua imagem
  assets:
    - assets/

# ==========================================
# CONFIGURAÇÃO DO ÍCONE DA APP
# ==========================================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon_app.png"